PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wgs: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX era: <http://data.europa.eu/949/>
PREFIX dcterms: <http://purl.org/dc/terms/>

CONSTRUCT {
	?operationalPoint rdf:type era:OperationalPoint ;
				era:opName ?opName ;
				era:uopid ?uopid .
}
WHERE {
    SELECT DISTINCT ?operationalPoint ?opName ?uopid
    WHERE {
        ?operationalPoint rdf:type era:OperationalPoint ;
            era:opName ?opName ;
            era:uopid ?uopid .
    }
}
